FROM tensorflow/tensorflow:2.12.0-gpu AS deps
ARG REQ_SHA="dev"
LABEL org.tinychat.reqsha=${REQ_SHA}
WORKDIR /app
COPY requirements.txt .
RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir --prefer-binary -r requirements.txt
