FROM tensorflow/tensorflow:2.12.0-gpu

WORKDIR /app
COPY requirements.txt ./
RUN pip --no-cache-dir install -r requirements.txt
RUN pip --no-cache-dir install matplotlib

COPY app.py profile.py ./

ENV EPOCHS=1
CMD ["python", "profile.py", "--quick", "--samples", "1000"]
