apiVersion: v1
kind: Namespace
metadata:
  name: tiny-chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-chat
  namespace: tiny-chat
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: tiny-chat
  template:
    metadata:
      labels:
        app: tiny-chat
    spec:
      containers:
      - name: tiny-chat
        image: tiny-chat:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
        - name: metrics
          containerPort: 9100
        env:
        - name: MAX_HISTORY
          value: "6"
        - name: REQUIRE_GPU
          value: "1"
        - name: ALLOW_CPU_FALLBACK
          value: "0"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
            nvidia.com/gpu: 1
          limits:
            cpu: 500m
            memory: 1Gi
            nvidia.com/gpu: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tiny-chat
  namespace: tiny-chat
spec:
  selector:
    app: tiny-chat
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: metrics
      port: 9100
      targetPort: metrics
