apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-profiler-monitor
  labels:
    app: gpu-profiler-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-profiler-monitor
  template:
    metadata:
      labels:
        app: gpu-profiler-monitor
    spec:
      restartPolicy: Always
      containers:
      - name: profiler-monitor
        image: nv-profiler:latest
        imagePullPolicy: IfNotPresent
        command: ["python","/app/profile.py"]
        args:
          - "--metrics-only"
          - "--sample-interval"
          - "5"
          - "--duration"
          - "0"
          - "--enable-dmon"
          - "--dmon-select"
          - "pucvmet"
          - "--output-dir"
          - "/tmp"
        resources: {}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-profiler-monitor
  labels:
    app: gpu-profiler-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-profiler-monitor
  template:
    metadata:
      labels:
        app: gpu-profiler-monitor
    spec:
      restartPolicy: Always
      containers:
      - name: profiler-monitor
        image: nv-profiler:latest
        imagePullPolicy: IfNotPresent
        command: ["python","/app/profile.py"]
        args:
          - "--metrics-only"
          - "--sample-interval"
          - "5"
          - "--duration"
          - "0"
          - "--enable-dmon"
          - "--dmon-select"
          - "pucvmet"
          - "--output-dir"
          - "/tmp"
        # No GPU resource request; relies on device plugin and driver permissions.
        resources: {}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
